### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by barak** [sanjayankur31/planet-neuroscience#1]
It would be nice if Planet Neuroscience generated its own RSS feed.

**Comment by sanjayankur31** [comment]
Yea - it's been on my TODO list. I'll hopefully get it done this weekend.

**Comment by sanjayankur31** [comment]
Both planets now have feeds among other things set up. Please do let me know if there are any enhancements you can think of. 

Cheers!

**Comment by barak** [comment]
Wow thanks, that's fantastic.
Will fwd any blogs I think should be added to either list.
Of course, some sort of voting system (collab filtering) so important stuff can be filtered up would be the biggest thing I could imagine doing to goose this up. But that's a hard problem, made harder by the fact that different people care about different things.

**Comment by sanjayankur31** [comment]
Yeah - the voting etc. will require a complete application. At the moment, it's literally just a feed aggregator that generates a static page. Maybe using pubpeer and other similar resources for post publication discussion would be a better idea than developing yet another app at the moment?

**Comment by barak** [comment]
Probably true, would completely change the character of this from simple to complicated.
